apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.name" . }}
  labels:
    app: {{ include "rafiki.name" . }}
    chart: {{ include "rafiki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "frontend.name" . }}
    release: {{ .Release.Name }}
