apiVersion: v1
kind: Service
metadata:
  name: {{ include "tigerbeetle.fullname" . }}
  labels: {{- include "tigerbeetle.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4242
      protocol: TCP
      name: http
  selector: {{- include "tigerbeetle.selectorLabels" . | nindent 4 }}
