name: us-treasury
services:
  us-treasury-mock-ase:
    hostname: us-treasury
    image: rafiki-mock-ase
    pull_policy: never
    build:
      context: ../..
      dockerfile: ./localenv/mock-account-servicing-entity/Dockerfile
    restart: always
    networks:
      - rafiki
    ports:
      - '3033:80'
    environment:
      LOG_LEVEL: debug
      PORT: 80
      SEED_FILE_LOCATION: /workspace/seed.yml
      KEY_FILE: /workspace/private-key.pem
      OPEN_PAYMENTS_URL: ${US_TREASURY_OPEN_PAYMENTS_URL:-https://us-treasury-backend}
      AUTH_SERVER_DOMAIN: ${US_TREASURY_AUTH_SERVER_DOMAIN:-http://localhost:3006}
      TESTNET_AUTOPEER_URL: ${TESTNET_AUTOPEER_URL}
      GRAPHQL_URL: http://us-treasury-backend:3001/graphql
      SIGNATURE_VERSION: 1
      SIGNATURE_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
      IDP_SECRET: 2pEcn2kkCclbOHQiGNEwhJ0rucATZhrA807HTm2rNXE=
      DISPLAY_NAME: US Treasury
      DISPLAY_ICON: treasury-icon.svg
      OPERATOR_TENANT_ID: 7097F83B-CB84-469E-96C6-2141C72E22C0
    volumes:
      - ../us-treasury/seed.yml:/workspace/seed.yml
      - ../us-treasury/private-key.pem:/workspace/private-key.pem
    depends_on:
      us-treasury-backend:
        condition: service_healthy

  us-treasury-backend:
    hostname: us-treasury-backend
    image: rafiki-backend
    pull_policy: never
    build:
      context: ../..
      dockerfile: ./packages/backend/Dockerfile.dev
    volumes:
      - type: bind
        source: ../../packages/backend/src
        target: /home/rafiki/packages/backend/src
        read_only: true
    restart: always
    privileged: true
    ports:
      - "6000:80"
      - "6001:3001"
      - "6002:3002"
      - '9242:9229'
    networks:
      - rafiki
    environment:
      NODE_ENV: development
      INSTANCE_NAME: US-TREASURY
      LOG_LEVEL: debug
      ADMIN_PORT: 3001
      CONNECTOR_PORT: 3002
      OPEN_PAYMENTS_PORT: 80
      DATABASE_URL: postgresql://us_treasury_backend:us_treasury_backend@shared-database/us_treasury_backend
      USE_TIGERBEETLE: false
      AUTH_SERVER_GRANT_URL: ${US_TREASURY_AUTH_SERVER_DOMAIN:-http://us-treasury-auth:3006}
      AUTH_SERVER_INTROSPECTION_URL: http://us-treasury-auth:3007
      AUTH_ADMIN_API_URL: 'http://us-treasury-auth:3003/graphql'
      AUTH_ADMIN_API_SECRET: 'rPoZpe9tVyBNCigm05QDco7WLcYa0xMao7lO5KG1XG4='
      AUTH_SERVICE_API_URL: 'http://us-treasury-auth:3011'
      ILP_ADDRESS: test.us-treasury
      ILP_CONNECTOR_URL: http://us-treasury-backend:6002
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      API_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
      WEBHOOK_URL: http://us-treasury/webhooks
      OPEN_PAYMENTS_URL: ${US_TREASURY_OPEN_PAYMENTS_URL:-http://us-treasury-backend}
      EXCHANGE_RATES_URL: http://us-treasury/rates
      REDIS_URL: redis://shared-redis:6379/6
      WALLET_ADDRESS_URL: ${US_TREASURY_WALLET_ADDRESS_URL:-https://us-treasury-backend/.well-known/pay}
      ENABLE_TELEMETRY: true
      ENABLE_ILP_TIMING: true
      KEY_ID: 7097F83B-CB84-469E-96C6-2141C72E22C0
      OPERATOR_TENANT_ID: 7097F83B-CB84-469E-96C6-2141C72E22C0
    depends_on:
      - shared-database
      - shared-redis
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/healthz"]
      start_period: 60s
      start_interval: 5s
      interval: 30s
      retries: 1
      timeout: 3s

  us-treasury-auth:
    hostname: us-treasury-auth
    image: rafiki-auth
    pull_policy: never
    build:
      context: ../..
      dockerfile: ./packages/auth/Dockerfile.dev
    volumes:
      - type: bind
        source: ../../packages/auth/src
        target: /home/rafiki/packages/auth/src
        read_only: true
    restart: always
    networks:
      - rafiki
    ports:
      - '6003:3003'
      - '6006:3006'
      - '9243:9229'
      - '6009:3009'
      - '6012:3011'
    environment:
      NODE_ENV: development
      AUTH_DATABASE_URL: postgresql://us_treasury_auth:us_treasury_auth@shared-database/us_treasury_auth
      AUTH_SERVER_URL: ${US_TREASURY_AUTH_SERVER_DOMAIN:-http://localhost:6006}
      REDIS_URL: redis://shared-redis:6379/7
      IDENTITY_SERVER_URL: http://localhost:3033/mock-idp/
      IDENTITY_SERVER_SECRET: 2pEcn2kkCclbOHQiGNEwhJ0rucATZhrA807HTm2rNXE=
      COOKIE_KEY: 42397d1f371dd4b8b7d0308a689a57c882effd4ea909d792302542af47e2cd37
      ADMIN_API_SECRET: rPoZpe9tVyBNCigm05QDco7WLcYa0xMao7lO5KG1XG4=
      OPERATOR_TENANT_ID: 7097F83B-CB84-469E-96C6-2141C72E22C0
      SERVICE_API_PORT: 3011
    depends_on:
      - shared-database
      - shared-redis

  us-treasury-admin:
    hostname: us-treasury-admin
    image: rafiki-frontend
    pull_policy: never
    build:
      context: ../..
      dockerfile: ./packages/frontend/Dockerfile.dev
    volumes:
      - type: bind
        source: ../../packages/frontend/app
        target: /home/rafiki/packages/frontend/app
        read_only: true
    restart: always
    networks:
      - rafiki
    ports:
      - '6011:5011'
    environment:
      PORT: 5011
      LOG_LEVEL: debug
      NODE_ENV: development
      GRAPHQL_URL: http://us-treasury-backend:3001/graphql
      OPEN_PAYMENTS_URL: https://us-treasury-backend/
      ENABLE_INSECURE_MESSAGE_COOKIE: true
      AUTH_ENABLED: false      
      SIGNATURE_VERSION: 1
      SIGNATURE_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
    depends_on:
      - us-treasury-backend