version: '3'
services:
  postgres:
    image: "postgres" # use latest official postgres version
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: testing
  redis:
    image: "redis"
    restart: unless-stopped
    ports:
      - "6380:6379"
  tigerbeetle:
    image: "wilsonianbcoil/tigerbeetle:latest"
    restart: unless-stopped
    ports:
      - "3001:3001"
    entrypoint: ["./tigerbeetle", "--cluster-id=0a5ca1ab1ebee11e", "--replica-index=0", "--replica-addresses=0.0.0.0:3001"]
volumes:
  database-data: # named volumes can be managed easier using docker-compose
