version: '3'
services:
  peer-auth:
    image: ghcr.io/interledger/rafiki-auth:latest
    restart: always
    networks:
      rafiki:
    environment:
      NODE_ENV: development
      AUTH_DATABASE_URL: postgresql://peerauth:peerauth@database/peerauth
  peer-backend:
    image: ghcr.io/interledger/rafiki-backend:latest
    restart: always
    privileged: true
    ports:
      - "4001:3001"
      - "4002:3002"
      - "4003:3003"
    networks:
      rafiki:
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      CONNECTOR_PORT: 3002
      DATABASE_URL: postgresql://peerbackend:peerbackend@database/peerbackend
      TIGERBEETLE_CLUSTER_ID: 0
      # Tigerbeetle will support DNS in future
      TIGERBEETLE_REPLICA_ADDRESSES: '["10.5.0.50:4342"]'
      NONCE_REDIS_KEY: test
      AUTH_SERVER_GRANT_URL: http://peer-auth
      AUTH_SERVER_INTROSPECTION_URL: http://peer-auth:3006/introspect
      ILP_ADDRESS: test.peer
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      ADMIN_KEY: admin
      ADMIN_URL: http://rafiki.peer:3001
      OPEN_PAYMENTS_URL: http://op.rafiki.peer:3003
      WEBHOOK_URL: https://end3sf6r22xva.x.pipedream.net
      OPEN_PAYMENTS_SPEC: https://raw.githubusercontent.com/interledger/open-payments/main/open-api-spec.yaml
      AUTH_SERVER_SPEC: https://raw.githubusercontent.com/interledger/open-payments/main/auth-server-open-api-spec.yaml
      PRICES_URL: http://peer-rates:3005/prices
      REDIS_URL: redis://redis:6379
  peer-rates:
    image: ghcr.io/interledger/rafiki-rates:latest
    restart: always
    networks:
      rafiki:
    environment:
      NODE_ENV: development
      PORT: 3005
