# Sanity check on merges with main.
# TODO: Use this workflow for publishing main
on:
  push:
    branches:
    - main

name: Sanity check main on merge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # NB: --check-cache is an important security check, see https://yarnpkg.com/features/zero-installs#does-it-have-security-implications
      - run: yarn install --frozen-lockfile --check-cache
      - run: yarn lint
      - run: yarn test
